INSERT INTO travelers.country (`name`, `country_code`) 
VALUES ('Aruba','ABW'),
('Afghanistan','AFG'),
('Angola','AGO'),
('Anguilla','AIA'),
('Albania','ALB'),
('Andorra','AND'),
('Netherlands Antilles','ANT'),
('United Arab Emirates','ARE'),
('Argentina','ARG'),
('Armenia','ARM'),
('American Samoa','ASM'),
('Antarctica','ATA'),
('French Southern territories','ATF'),
('Antigua and Barbuda','ATG'),
('Australia','AUS'),
('Austria','AUT'),
('Azerbaijan','AZE'),
('Burundi','BDI'),
('Belgium','BEL'),
('Benin','BEN'),
('Burkina Faso','BFA'),
('Bangladesh','BGD'),
('Bulgaria','BGR'),
('Bahrain','BHR'),
('Bahamas','BHS'),
('Bosnia and Herzegovina','BIH'),
('Belarus','BLR'),
('Belize','BLZ'),
('Bermuda','BMU'),
('Bolivia','BOL'),
('Brazil','BRA'),
('Barbados','BRB'),
('Brunei','BRN'),
('Bhutan','BTN'),
('Bouvet Island','BVT'),
('Botswana','BWA'),
('Central African Republic','CAF'),
('Canada','CAN'),
('Cocos (Keeling) Islands','CCK'),
('Switzerland','CHE'),
('Chile','CHL'),
('China','CHN'),
('CÃ´te dÂ’Ivoire','CIV'),
('Cameroon','CMR'),
('Congo, The Democratic Republic of the','COD'),
('Congo','COG'),
('Cook Islands','COK'),
('Colombia','COL'),
('Comoros','COM'),
('Cape Verde','CPV'),
('Costa Rica','CRI'),
('Cuba','CUB'),
('Christmas Island','CXR'),
('Cayman Islands','CYM'),
('Cyprus','CYP'),
('Czech Republic','CZE'),
('Germany','DEU'),
('Djibouti','DJI'),
('Dominica','DMA'),
('Denmark','DNK'),
('Dominican Republic','DOM'),
('Algeria','DZA'),
('Ecuador','ECU'),
('Egypt','EGY'),
('Eritrea','ERI'),
('Western Sahara','ESH'),
('Spain','ESP'),
('Estonia','EST'),
('Ethiopia','ETH'),
('Finland','FIN'),
('Fiji Islands','FJI'),
('Falkland Islands','FLK'),
('France','FRA'),
('Faroe Islands','FRO'),
('Micronesia, Federated States of','FSM'),
('Gabon','GAB'),
('United Kingdom','GBR'),
('Georgia','GEO'),
('Ghana','GHA'),
('Gibraltar','GIB'),
('Guinea','GIN'),
('Guadeloupe','GLP'),
('Gambia','GMB'),
('Guinea-Bissau','GNB'),
('Equatorial Guinea','GNQ'),
('Greece','GRC'),
('Grenada','GRD'),
('Greenland','GRL'),
('Guatemala','GTM'),
('French Guiana','GUF'),
('Guam','GUM'),
('Guyana','GUY'),
('Hong Kong','HKG'),
('Heard Island and McDonald Islands','HMD'),
('Honduras','HND'),
('Croatia','HRV'),
('Haiti','HTI'),
('Hungary','HUN'),
('Indonesia','IDN'),
('India','IND'),
('British Indian Ocean Territory','IOT'),
('Ireland','IRL'),
('Iran','IRN'),
('Iraq','IRQ'),
('Iceland','ISL'),
('Israel','ISR'),
('Italy','ITA'),
('Jamaica','JAM'),
('Jordan','JOR'),
('Japan','JPN'),
('Kazakstan','KAZ'),
('Kenya','KEN'),
('Kyrgyzstan','KGZ'),
('Cambodia','KHM'),
('Kiribati','KIR'),
('Saint Kitts and Nevis','KNA'),
('South Korea','KOR'),
('Kuwait','KWT'),
('Laos','LAO'),
('Lebanon','LBN'),
('Liberia','LBR'),
('Libyan Arab Jamahiriya','LBY'),
('Saint Lucia','LCA'),
('Liechtenstein','LIE'),
('Sri Lanka','LKA'),
('Lesotho','LSO'),
('Lithuania','LTU'),
('Luxembourg','LUX'),
('Latvia','LVA'),
('Macao','MAC'),
('Morocco','MAR'),
('Monaco','MCO'),
('Moldova','MDA'),
('Madagascar','MDG'),
('Maldives','MDV'),
('Mexico','MEX'),
('Marshall Islands','MHL'),
('Macedonia','MKD'),
('Mali','MLI'),
('Malta','MLT'),
('Myanmar','MMR'),
('Mongolia','MNG'),
('Northern Mariana Islands','MNP'),
('Mozambique','MOZ'),
('Mauritania','MRT'),
('Montserrat','MSR'),
('Martinique','MTQ'),
('Mauritius','MUS'),
('Malawi','MWI'),
('Malaysia','MYS'),
('Mayotte','MYT'),
('Namibia','NAM'),
('New Caledonia','NCL'),
('Niger','NER'),
('Norfolk Island','NFK'),
('Nigeria','NGA'),
('Nicaragua','NIC'),
('Niue','NIU'),
('Netherlands','NLD'),
('Norway','NOR'),
('Nepal','NPL'),
('Nauru','NRU'),
('New Zealand','NZL'),
('Oman','OMN'),
('Pakistan','PAK'),
('Panama','PAN'),
('Pitcairn','PCN'),
('Peru','PER'),
('Philippines','PHL'),
('Palau','PLW'),
('Papua New Guinea','PNG'),
('Poland','POL'),
('Puerto Rico','PRI'),
('North Korea','PRK'),
('Portugal','PRT'),
('Paraguay','PRY'),
('Palestine','PSE'),
('French Polynesia','PYF'),
('Qatar','QAT'),
('RÃ©union','REU'),
('Romania','ROM'),
('Russian Federation','RUS'),
('Rwanda','RWA'),
('Saudi Arabia','SAU'),
('Sudan','SDN'),
('Senegal','SEN'),
('Singapore','SGP'),
('South Georgia and the South Sandwich Islands','SGS'),
('Saint Helena','SHN'),
('Svalbard and Jan Mayen','SJM'),
('Solomon Islands','SLB'),
('Sierra Leone','SLE'),
('El Salvador','SLV'),
('San Marino','SMR'),
('Somalia','SOM'),
('Saint Pierre and Miquelon','SPM'),
('Sao Tome and Principe','STP'),
('Suriname','SUR'),
('Slovakia','SVK'),
('Slovenia','SVN'),
('Sweden','SWE'),
('Swaziland','SWZ'),
('Seychelles','SYC'),
('Syria','SYR'),
('Turks and Caicos Islands','TCA'),
('Chad','TCD'),
('Togo','TGO'),
('Thailand','THA'),
('Tajikistan','TJK'),
('Tokelau','TKL'),
('Turkmenistan','TKM'),
('East Timor','TMP'),
('Tonga','TON'),
('Trinidad and Tobago','TTO'),
('Tunisia','TUN'),
('Turkey','TUR'),
('Tuvalu','TUV'),
('Taiwan','TWN'),
('Tanzania','TZA'),
('Uganda','UGA'),
('Ukraine','UKR'),
('United States Minor Outlying Islands','UMI'),
('Uruguay','URY'),
('United States','USA'),
('Uzbekistan','UZB'),
('Holy See (Vatican City State)','VAT'),
('Saint Vincent and the Grenadines','VCT'),
('Venezuela','VEN'),
('Virgin Islands, British','VGB'),
('Virgin Islands, U.S.','VIR'),
('Vietnam','VNM'),
('Vanuatu','VUT'),
('Wallis and Futuna','WLF'),
('Samoa','WSM'),
('Yemen','YEM'),
('Yugoslavia','YUG'),
('South Africa','ZAF'),
('Zambia','ZMB'),
('Zimbabwe','ZWE');